### PR TITLE
Hiding Selection Outline When Out-Of-Bounds

### LINKED ISSUE #84: Selection Active When In Menu
## Summary
The tile selection still follows the mouse cursor even when hovering over the menu bar. I would expect the selection to be not active.

top-menu-selection-wrong

### PR DESCRIPTION
**Pull request by PythooonUser**
## Summary
Fixes #84. Hides the selection outline when hovering over a tile that is out-of-bounds. That also includes when hovering over the menu bar. Left clicking is not affected and will still select the nearest tile.

issue-84-fix

### CODE REVIEW

File: DelvEdit/src/com/interrupt/dungeoneer/editor/EditorApplication.java [hunk 1]
```diff
@@ -736,15 +736,30 @@ else if(e == Editor.selection.hovered) {
...
 
-						// Tile selection bounding
+				// Tile selection bounding
+				boolean isOutOfBounds = false;
 				Editor.selection.tiles.x = (int)end.x;
 				Editor.selection.tiles.y = (int)end.z;
 
-				if(Editor.selection.tiles.x < 0) Editor.selection.tiles.x = 0;
-				if(Editor.selection.tiles.x >= level.width) Editor.selection.tiles.x = level.width - 1;
+				if(Editor.selection.tiles.x < 0) {
```
Comment (joshuaskelly) [inline DelvEdit/src/com/interrupt/dungeoneer/editor/EditorApplication.java:744]: The `TileSelection` object has a `contains()` method and a `getBounds()` method. You might use one of those to simply this logic?

**Review by joshuaskelly — CHANGES_REQUESTED** [review]
Could you see if you can simplify the logic I called out?

File: DelvEdit/src/com/interrupt/dungeoneer/editor/EditorApplication.java (hunk 1 above)
Comment (PythooonUser) [reply DelvEdit/src/com/interrupt/dungeoneer/editor/EditorApplication.java:754]: Mmh. `contains()` only works on tiles *inside* the selection. Of course I could check if `0` and `widht/height` are part of the selection. `getBounds()` returns the bounds of the selection. So essentially just `x` and `y` coordinates in a struct-like object, so it doesn't change how the algorithm would work. I could create a new method that returns whether the selection is valid/out-of-bounds instead and move the logic in there? But it would be depending on the level properties.

Comment (PythooonUser) [reply DelvEdit/src/com/interrupt/dungeoneer/editor/EditorApplication.java]: Okay. I split it into `outOfLevelBounds()` and `cropToLevelBounds()`. I don't think that additional dependency on the level is too bad. Thoughts?

Comment (PythooonUser) [reply DelvEdit/src/com/interrupt/dungeoneer/editor/EditorApplication.java]: Additionally I overloaded the `clear` method to simplify more logic. I also started adding one-line JavaDoc comments.

Comment (joshuaskelly) [reply DelvEdit/src/com/interrupt/dungeoneer/editor/EditorApplication.java]: There are a few points that need clarifying. 
1. TileSelections are collections of tiles. They should make no assumptions about their shape.
2. TileSelections are independent of levels, and can be copy and pasted between levels.

Comment (joshuaskelly) [reply DelvEdit/src/com/interrupt/dungeoneer/editor/EditorApplication.java]: Here is a quick hack I implemented in a local copy of your PR:
```java
// Tile selection bounding
Editor.selection.tiles.x = (int)end.x;
Editor.selection.tiles.y = (int)end.z;

TileSelection entireLevel = TileSelection.Rect(0, 0, level.width, level.height);
boolean isOutOfBounds = !entireLevel.contains((int)end.x, (int)end.z);

shouldDrawBox = !isOutOfBounds && shouldDrawBox;
```
In practice the `entireLevel` tile selection only changes when new a level, so it should be a private field on `EditorApplication` or something like that.

Comment (PythooonUser) [reply DelvEdit/src/com/interrupt/dungeoneer/editor/EditorApplication.java]: Ah, okay. That sounds good. I will have a look.

**Review by joshuaskelly — APPROVED** [review]
This is so clean and tidy!
