### PR TITLE
Loading Levels Not Validated

### LINKED ISSUE #79: Loading Levels Not Validated
loading-wrong

## Summary
Any file can be loaded. Even ones that do not exist. They default to a new project layout. I would expect an error message in that case.

## Work
- [x] Add ability to show error messages
- [x] Allow only valid level extensions to be loaded
- [x] Check if level could be loaded successfully

### PR DESCRIPTION
**Pull request by PythooonUser**
grafik

Fixes #79.

Adds
- Editor title only updated when level successfully loaded
- Warning dialog when invalid extension
- Warning dialog when non-existing file
- Warning dialog when unsuccessful level load (e.g. invalid level data)
- Simplified loading logic when handling different file types

### CODE REVIEW

**Comment by PythooonUser** [comment]
When trying to load a `.dat` file with contents `{}` it crashes:

`Exception in thread "LWJGL Application" java.lang.NullPointerException: Cannot invoke "com.badlogic.gdx.utils.Array.iterator()" because "this.level.entities" is null
        at com.interrupt.dungeoneer.editor.EditorApplication.refreshLights(EditorApplication.java:2681)
        at com.interrupt.dungeoneer.editor.EditorApplication.refresh(EditorApplication.java:2647)
        at com.interrupt.dungeoneer.editor.file.EditorFile.openInternal(EditorFile.java:299)
        at com.interrupt.dungeoneer.editor.file.EditorFile.access$3(EditorFile.java:273)
        at com.interrupt.dungeoneer.editor.file.EditorFile$4.result(EditorFile.java:260)
        at com.interrupt.dungeoneer.editor.ui.FilePicker$10.result(FilePicker.java:390)
        at com.badlogic.gdx.scenes.scene2d.ui.Dialog$2.changed(Dialog.java:92)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:183)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:154)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:131)
        at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:94)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:59)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:350)
        at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:124)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:342)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
`

**Comment by PythooonUser** [comment]
When loading a `.dat` file with invalid JSON the error message is not nice:

`[EditorFile] Error reading file: D:/Spiele/steamapps/common/Delver/delver/levels/invalid-syntax.dat Cannot load 'invalid-syntax.dat'.`

File: DelvEdit/src/com/interrupt/dungeoneer/editor/file/EditorFile.java [hunk 1]
```diff
@@ -269,58 +271,95 @@ public boolean result(boolean success, FileHandle result) {
...
+            Editor.app.history = new EditorHistory();
+            Editor.app.history.saveState(Editor.app.level);
+            Editor.app.file.markClean();
+
+            Editor.options.addRecentlyOpenedFile(file.path());
+
+            Editor.app.clearEntitySelection();
+            Editor.app.viewSelected();
+        } else {
+            showWarningDialog("File does not exist. Cannot load '" + name + "'.");
```
Comment (joshuaskelly) [inline DelvEdit/src/com/interrupt/dungeoneer/editor/file/EditorFile.java:320]: A nice improvement would be to remove the file from recently open file list. Probably `Editor.options.removeRecentlyOpenedFile(file.path())`

File: DelvEdit/src/com/interrupt/dungeoneer/editor/ui/WarningDialog.java [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+import com.badlogic.gdx.scenes.scene2d.ui.Skin;
+
+public class WarningDialog extends Dialog {
+    public WarningDialog(Skin skin, String warning) {
+        super("Warning", skin);
+
+        text(warning);
+        getContentTable().row();
+
+        button("Understood", true);
```
Comment (joshuaskelly) [inline DelvEdit/src/com/interrupt/dungeoneer/editor/ui/WarningDialog.java:13]: Maybe change "Understood" to "Close"?

**Review by joshuaskelly — APPROVED** [review]
I left some suggestions, but otherwise the changes look good.

File: DelvEdit/src/com/interrupt/dungeoneer/editor/file/EditorFile.java (hunk 1 above)
Comment (PythooonUser) [reply DelvEdit/src/com/interrupt/dungeoneer/editor/file/EditorFile.java:321]: Yes, true. In case that file does not exist anymore, we can remove it from the list.

File: DelvEdit/src/com/interrupt/dungeoneer/editor/ui/WarningDialog.java (hunk 2 above)
Comment (PythooonUser) [reply DelvEdit/src/com/interrupt/dungeoneer/editor/ui/WarningDialog.java]: Sounds more "professional", true.

File: DelvEdit/src/com/interrupt/dungeoneer/editor/file/EditorFile.java [hunk 3]
```diff
@@ -269,58 +271,96 @@ public boolean result(boolean success, FileHandle result) {
...
+
+            try {
+                if (name.endsWith(".png")) {
+                    level = loadPngFile(file);
+                } else if (name.endsWith(".bin")) {
+                    level = loadBinFile(file);
+                } else if (name.endsWith(".dat")) {
+                    level = loadDatFile(file);
+                } else {
+                    showWarningDialog("Unkown extension. Cannot load '" + name + "'.");
```
Comment (joshuaskelly) [inline DelvEdit/src/com/interrupt/dungeoneer/editor/file/EditorFile.java:289]: Typo here:
"Unknown"

**Review by joshuaskelly — APPROVED** [review]
One little typo!

File: DelvEdit/src/com/interrupt/dungeoneer/editor/file/EditorFile.java (hunk 3 above)
Comment (PythooonUser) [reply DelvEdit/src/com/interrupt/dungeoneer/editor/file/EditorFile.java]: Fixed. Thanks!
