### PR TITLE
Fixes/238 treasure hunter achievement

### LINKED ISSUE #238: Treasure Hunter Achievement is Inconsistent
## Summary
Many players complain about being unable to get this achievement. After some investigation I've determined a few reasons for this.

1. The achievement is only checked on the game over screen and not on the win screen.
2. The `dealtAchievements` field is never reset after the game over screen. So it can only be earned on the first run of an app session.

### PR DESCRIPTION
**Pull request by PythooonUser**
Fixes #238.

### Summary
- The "Treasure Hunter" achievement is now immediately being dealt when a player collects 300 gold or more in a single run
- The stats screen can no longer show negative amount of gold collected (ignores gold spent)
- When quitting a game from the pause menu, we now properly store gold in the progression and therefore it is correctly displayed on the save slot

⚠️ Players have to be aware that, because of how gold is now tracked in the player history - and we don't migrate `goldAtStartOfRun` to the player history, the achievement can only be granted with a ~~NEW SAVE~~ NEW RUN.

### Testing
- Start a new game
- Collect 300 gold or more in one run
- See that the achievement gets dealt

### CODE REVIEW

File: core/src/main/java/com/interrupt/dungeoneer/game/Progression.java [hunk 1]
```diff
@@ -15,8 +13,6 @@ public class Progression {
 	public int messagesFound = 0;
 	public boolean won = false;
 
-	public int goldAtStartOfRun = 0;
```
Comment (PythooonUser) [inline core/src/main/java/com/interrupt/dungeoneer/game/Progression.java:18]: Removing this causes no harm. We only get a warning: `[Serialization] Warning: Unknown field: goldAtStartOfRun for class: class com.interrupt.dungeoneer.game.Progression`

Comment (Interrupt) [reply core/src/main/java/com/interrupt/dungeoneer/game/Progression.java:18]: Thanks for checking!

**Review by Interrupt — APPROVED** [review]
