### PR TITLE
Fixes issue with keybinds not working after loading the game

### LINKED ISSUE #201: Some Players Cannot Save Keybinds
## Summary
Some players are able to rebind keys, but the bindings do not save. Other options do save, but not the keybinds.

### PR DESCRIPTION
**Pull request by joshuaskelly**
## Summary
Fixes issue with custom keybinds not working after relaunching the game. The issue was keybinds are set by the GamepadManager called in `Game.init()` which is called before `Options.loadOptions()` in `SplashScreen.java`. This results in using a temp instance of Options which are all the default keybinds.

## Fix
I decoupled setting gamepad bindings and key bindings. We set the keybindings whenever we load the options file and load the gamepad bindings once the GamepadManager has been initialized.

Fixes #201

### CODE REVIEW

File: Dungeoneer/src/com/interrupt/dungeoneer/input/GamepadManager.java [hunk 1]
```diff
@@ -302,23 +302,30 @@ public void init() {
...
-			controllerMapping.put(controller, new GamepadDefinition(new Ouya()));
-		else if (controllerName.contains("moga"))
-			controllerMapping.put(controller, new GamepadDefinition(new MogaProPad()));
-		else
-			controllerMapping.put(controller, new GamepadDefinition(new Xbox360Pad()));
-
-		Options.SetInputOptions(controllerMapping.get(controller));
+        String controllerName = controller.getName().toLowerCase();
+
+        if (controllerName.contains("microsoft corporatio controller")) {
```
Comment (PythooonUser) [inline Dungeoneer/src/com/interrupt/dungeoneer/input/GamepadManager.java:309]: `corporation`?

**Review by PythooonUser — APPROVED** [review]

File: Dungeoneer/src/com/interrupt/dungeoneer/input/GamepadManager.java (hunk 1 above)
Comment (joshuaskelly) [reply Dungeoneer/src/com/interrupt/dungeoneer/input/GamepadManager.java:309]: This is the actual name. 🙃

Comment (GadyZ) [reply Dungeoneer/src/com/interrupt/dungeoneer/input/GamepadManager.java:309]: Thanks for the fix Joshua!

> 
> 
> `corporation`?

Microsoft probably trying to recreate the Roman empire or something :)

**Review by Interrupt — COMMENTED** [review]
Looks good to me!
